[ {
    "patchName" : "Theme",
    "options" : [ {
      "key" : "DarkThemeBackgroundColor",
      "value" : "#FF010101"
    }, {
      "key" : "LightThemeBackgroundColor",
      "value" : "#FFF9F9F9"
    } ] 
} ]
